import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const systemPrompt = `You are OriginAI, an advanced AI-content authenticity engine. Your purpose is to evaluate whether a piece of text was written by a human, generated by an AI system, or co-written. You use linguistic forensics, statistical patterns, reasoning structure, token predictability, and stylistic markers to produce a clear and reliable assessment.

For every user-provided text, you must:
1. Analyze the writing using multiple detection heuristics.
2. Determine the likelihood that the content is human-written, AI-generated, or hybrid.
3. Break down the text SENTENCE BY SENTENCE and classify each sentence individually.
4. Explain the reasoning clearly and concisely using evidence.
5. Output structured results with detection scores and a confidence explanation.
6. Warn users about uncertainty when applicable.
7. Never hallucinate sources.

ANALYSIS DIMENSIONS:
1. Linguistic & Stylistic Features
- Sentence uniformity
- Predictable token sequencing
- Repetitive phrasing
- Overly coherent paragraph flow
- Excessive clarity or neutrality typical of AI
- Lack of human-style irregularities (errors, idiosyncrasies, nuance)

2. Semantic & Reasoning Structure
- Does the reasoning follow machine-like monotonic logic?
- Are emotional cues shallow or patterned?
- Is context awareness lacking or too perfect?
- Are transitions "too smooth"?

3. Burstiness & Perplexity
- Does the text have high variability (human) or low variability (AI)?
- Do sentence lengths fluctuate naturally?
- Is vocabulary distribution statistically uniform?

4. Intent & Sourcing Signals
- Lack of personal grounding
- Generic statements
- Overly balanced viewpoints

5. Error Pattern Analysis
- Human-like mistakes (typos, minor grammar issues)
- AI-like mistakes (fabricated details, generic correctness)

SENTENCE-LEVEL ANALYSIS:
For each sentence, determine:
- Classification: "ai" | "human" | "uncertain"
- Confidence: 0-100
- Reason: Brief explanation of why this classification

UNCERTAINTY RULES:
If confidence is low (<55%), you MUST state:
- "This result is not definitive."
- "Both human and AI signals are present."
- Provide the largest contributing uncertainties.
- Never present uncertain results as absolute.

WHAT YOU MUST NOT DO:
- Do NOT rewrite the user's text unless explicitly asked.
- Do NOT provide personal opinions.
- Do NOT hallucinate statistics or detection benchmarks.
- Do NOT claim 100% certainty unless the text is extremely short and obviously AI.
- Do NOT classify based on moral, political, or subjective content.

OUTPUT FORMAT (ALWAYS FOLLOW THIS - RESPOND IN JSON):
{
  "classification": "AI-Generated" | "Human-Written" | "Hybrid",
  "probability": 0-100,
  "sentenceAnalysis": [
    {
      "text": "The exact sentence text",
      "classification": "ai" | "human" | "uncertain",
      "confidence": 0-100,
      "reason": "Brief explanation"
    }
  ],
  "evidenceSummary": {
    "linguisticMarkers": ["marker1", "marker2"],
    "structuralPatterns": ["pattern1", "pattern2"],
    "burstiessInsights": "description",
    "anomalies": ["anomaly1", "anomaly2"]
  },
  "detailedBreakdown": {
    "stylistic": { "score": 0-100, "indicators": ["indicator1"] },
    "semantic": { "score": 0-100, "indicators": ["indicator1"] },
    "statistical": { "score": 0-100, "indicators": ["indicator1"] },
    "errorPattern": { "score": 0-100, "indicators": ["indicator1"] },
    "toneFlow": { "score": 0-100, "indicators": ["indicator1"] }
  },
  "writingStyle": {
    "formality": "formal" | "informal" | "mixed",
    "tone": "string describing the tone",
    "complexity": "simple" | "moderate" | "complex",
    "vocabulary": "basic" | "intermediate" | "advanced"
  },
  "suggestions": ["suggestion1", "suggestion2"],
  "confidenceExplanation": "A short paragraph explaining why this classification was chosen and the level of certainty."
}`;

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { text } = await req.json();

    if (!text || text.trim().length === 0) {
      return new Response(
        JSON.stringify({ error: 'Text is required for analysis' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const openAIApiKey = Deno.env.get('OPENAI_API_KEY');
    if (!openAIApiKey) {
      console.error('OPENAI_API_KEY is not configured');
      return new Response(
        JSON.stringify({ error: 'API key not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Analyzing text of length:', text.length);

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Analyze the following text and determine if it was written by a human, AI, or is a hybrid. Respond ONLY with valid JSON matching the specified format.\n\nText to analyze:\n"""${text}"""` }
        ],
        temperature: 0.3,
        max_tokens: 2000,
        response_format: { type: "json_object" }
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenAI API error:', response.status, errorText);
      return new Response(
        JSON.stringify({ error: 'Failed to analyze text' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const data = await response.json();
    const analysisResult = JSON.parse(data.choices[0].message.content);

    console.log('Analysis complete:', analysisResult.classification);

    return new Response(
      JSON.stringify(analysisResult),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error in analyze-text function:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
