import { Download, Copy, Share2, Check, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useState } from "react";
import type { AnalysisResult } from "@/types/analysis";

interface ExportActionsProps {
  result: AnalysisResult;
  originalText: string;
}

export const ExportActions = ({ result, originalText }: ExportActionsProps) => {
  const [copied, setCopied] = useState(false);

  const generateReport = () => {
    const lines = [
      "ORIGINAI ANALYSIS REPORT",
      "=" .repeat(40),
      `Generated: ${new Date().toLocaleString()}`,
      "",
      `CLASSIFICATION: ${result.classification}`,
      `AI PROBABILITY: ${result.probability}%`,
    ];

    if (result.confidenceLevel) {
      lines.push(`CONFIDENCE LEVEL: ${result.confidenceLevel.replace(/_/g, ' ').toUpperCase()}`);
    }

    if (result.aiPercentage !== undefined) {
      lines.push("", `AI Content: ${result.aiPercentage}%`);
    }
    if (result.humanPercentage !== undefined) {
      lines.push(`Human Content: ${result.humanPercentage}%`);
    }

    lines.push(
      "",
      "ANALYZED TEXT:",
      originalText.substring(0, 500) + (originalText.length > 500 ? '...' : ''),
      ""
    );

    if (result.readabilityMetrics) {
      lines.push(
        "READABILITY METRICS:",
        `- Flesch-Kincaid Grade: ${result.readabilityMetrics.fleschKincaidGrade}`,
        `- Flesch Reading Ease: ${result.readabilityMetrics.fleschReadingEase}`,
        `- Gunning Fog Index: ${result.readabilityMetrics.gunningFogIndex}`,
        `- Readability Level: ${result.readabilityMetrics.readabilityLevel}`,
        ""
      );
    }

    if (result.advancedMetrics) {
      lines.push(
        "ADVANCED METRICS:",
        `- Perplexity Score: ${result.advancedMetrics.perplexityScore}%`,
        `- Burstiness Score: ${result.advancedMetrics.burstinessScore}%`,
        `- Vocabulary Richness: ${result.advancedMetrics.vocabularyRichness}%`,
        ""
      );
    }

    lines.push(
      "DETAILED BREAKDOWN:",
      `- Stylistic: ${result.detailedBreakdown.stylistic.score}%`,
      `- Semantic: ${result.detailedBreakdown.semantic.score}%`,
      `- Statistical: ${result.detailedBreakdown.statistical.score}%`,
      `- Error Patterns: ${result.detailedBreakdown.errorPattern.score}%`,
      `- Tone & Flow: ${result.detailedBreakdown.toneFlow.score}%`
    );

    if (result.detailedBreakdown.neuralPatterns) {
      lines.push(`- Neural Patterns: ${result.detailedBreakdown.neuralPatterns.score}%`);
    }

    lines.push("");

    if (result.evidenceSummary.linguisticMarkers.length > 0) {
      lines.push(`Linguistic Markers: ${result.evidenceSummary.linguisticMarkers.join(', ')}`);
    }
    if (result.evidenceSummary.structuralPatterns.length > 0) {
      lines.push(`Structural Patterns: ${result.evidenceSummary.structuralPatterns.join(', ')}`);
    }
    if (result.evidenceSummary.aiSignatures && result.evidenceSummary.aiSignatures.length > 0) {
      lines.push(`AI Signatures: ${result.evidenceSummary.aiSignatures.join(', ')}`);
    }
    if (result.evidenceSummary.humanSignatures && result.evidenceSummary.humanSignatures.length > 0) {
      lines.push(`Human Signatures: ${result.evidenceSummary.humanSignatures.join(', ')}`);
    }

    if (result.writingStyle) {
      lines.push(
        "",
        "WRITING STYLE:",
        `- Formality: ${result.writingStyle.formality}`,
        `- Tone: ${result.writingStyle.tone}`,
        `- Complexity: ${result.writingStyle.complexity}`,
        `- Vocabulary: ${result.writingStyle.vocabulary}`
      );
      if (result.writingStyle.voice) lines.push(`- Voice: ${result.writingStyle.voice}`);
      if (result.writingStyle.perspective) lines.push(`- Perspective: ${result.writingStyle.perspective}`);
    }

    if (result.humanizationTips && result.humanizationTips.length > 0) {
      lines.push("", "HUMANIZATION TIPS:");
      result.humanizationTips.forEach(tip => {
        lines.push(`- [${tip.priority.toUpperCase()}] ${tip.tip}`);
      });
    }

    lines.push(
      "",
      "ANALYSIS SUMMARY:",
      result.confidenceExplanation
    );

    if (result.technicalNotes) {
      lines.push("", "TECHNICAL NOTES:", result.technicalNotes);
    }

    lines.push("", "---", "Report generated by OriginAI");

    return lines.join('\n');
  };

  const copyToClipboard = async () => {
    const report = generateReport();
    await navigator.clipboard.writeText(report);
    setCopied(true);
    toast.success("Full report copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const exportJSON = () => {
    const data = {
      ...result,
      originalText,
      exportedAt: new Date().toISOString(),
    };
    
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `originai-analysis-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Analysis exported as JSON!");
  };

  const exportTXT = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `originai-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  };

  const shareResult = async () => {
    const shareText = `OriginAI Analysis: ${result.classification} - ${result.probability}% AI probability`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: "OriginAI Analysis",
          text: shareText,
        });
      } catch (err) {
        await navigator.clipboard.writeText(shareText);
        toast.success("Share text copied to clipboard!");
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      toast.success("Share text copied to clipboard!");
    }
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={copyToClipboard}
        className="gap-2"
      >
        {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
        {copied ? "Copied!" : "Copy Report"}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={exportTXT}
        className="gap-2"
      >
        <FileText className="w-4 h-4" />
        Download TXT
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={exportJSON}
        className="gap-2"
      >
        <Download className="w-4 h-4" />
        Export JSON
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={shareResult}
        className="gap-2"
      >
        <Share2 className="w-4 h-4" />
        Share
      </Button>
    </div>
  );
};
